### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by avidican92** [ruqqus/ruqqus#621]
After trying to execute the app by te line `gunicorn ruqqus.__main__:app -b 127.0.0.1 -w 3 -k gevent --worker-connections 6 --preload --max-requests 5000 --max-requests-jitter 500`

I get this 

```
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/ruqqus/ruqqus/__main__.py", line 54, in <module>
    "SERVER_NAME", None)).rstrip()
AttributeError: 'NoneType' object has no attribute 'rstrip'

```

Anyone could provide a step by step full install guide for fresh servers running centos or ubuntu ?
Tkx

**Comment by CrystalVulpine** [comment]
You have to set those as environment variables (just put something random). They didn't exist until recently so there are no instructions for them, you'll just have to keep setting them until there's no more left.

**Comment by Shatterbrain** [comment]
Use my `docker-compose` branch. https://github.com/ruqqus/ruqqus/pull/614

**Comment by avidican92** [comment]
> Use my `docker-compose` branch. #614
> If you're asking because you actually want to run an instance for serious non-development purposes, you can reference that branch's docker-compose.yml for all of the environment variables you'll need.
` git clone https://github.com/Shatterbrain/ruqqus.git` does not import the docker.yml version.
May you provide a steps guide for fresh Linux servers?
